# Generated by Django 6.0.1 on 2026-02-03 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='is_synced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendance',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
